<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
          http://maven.apache.org/POM/4.0.0
          https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.jamiibank</groupId>
        <artifactId>jamiibank-integrations</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>jamii-savings</artifactId>
    <packaging>carbon/application</packaging>
    <name>Jamii Bank Integration</name>

    <build>
        <plugins>

            <plugin>
                <groupId>org.wso2.maven</groupId>
                <artifactId>maven-car-plugin</artifactId>
                <version>5.3.7</version>
                <extensions>true</extensions>
            </plugin>

        </plugins>
    </build>

</project>
