<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
          http://maven.apache.org/POM/4.0.0
          https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.jamiibank</groupId>
    <artifactId>jamiibank-integrations</artifactId>
    <version>1.0.0</version>

    <packaging>pom</packaging>

    <name>Jamii Bank Integrations</name>

    <modules>
        <module>integrations</module>
    </modules>

    <repositories>
        <repository>
            <id>wso2-public</id>
            <name>WSO2 Public Repository</name>
            <url>
                https://maven.wso2.org/nexus/content/groups/wso2-public/
            </url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>wso2-public</id>
            <name>WSO2 Public Repository</name>
            <url>
                https://maven.wso2.org/nexus/content/groups/wso2-public/
            </url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

</project>
